#!/bin/bash
set -e

SCRIPT_HOME="$(cd "$(dirname "$(readlink `which dao`)")" && pwd)"

set_env () {
  if [[ "$SHELL" =~ .*fish ]]; then
    dao env | source -
  else
    $(dao env)
  fi
}

start_daod () {
  pgrep -f 'daod' || daod
}

create_vm () {
  docker-machine create  --driver virtualbox --virtualbox-disk-size "10000" --virtualbox-memory "2048" dao-dev
  docker-machine ssh dao-dev sudo "sed -r \"s/EXTRA_ARGS='(.*?)'/EXTRA_ARGS='\1 --bip 10.100.200.1\/24'/\" /var/lib/boot2docker/profile > tmp && sudo mv tmp /var/lib/boot2docker/profile"
  docker-machine stop dao-dev
  docker-machine start dao-dev
  #set_env
  #start_daod
}

# Parse commands
case "$1" in
  vm)
    case "$2" in
      create)
        create_vm
        ;;

      *)
        docker-machine ${@:2} dao-dev
        ;;
    esac
    ;;

  update)
    cd $SCRIPT_HOME
    git pull
    ;;

  *)
    docker-compose $@
    ;;
esac
